### ISSUE TITLE
Rest bar overview

### ISSUE THREAD

**Issue by markusmo3** [datmeal/lostarkchecklist#20]
Playing multiple alts is a hassle if you don't have enough time in the day to do all of them.
It would be really nice if were able to track the rest bonus each one has, so that I can run them only if I have that rest bonus.

Another suggestion that plays into this: automatic daily/weekly reset, such that when I didn't do my chaos/guardian etc, I automatically gain the rest bonus in the app.

**Comment by datmeal** [comment]
Hey, thanks for the input!
If you click the box with your character's class, it should open up an 'advanced edit' menu where you can turn on rest bonus tracking, then the rest bonus will be tracked semi-automatically based on when you click the reset button. Let me know if that works!

Auto resets would be very cool to implement for sure, I've had some people ask for this before as well but it's a bit difficult to do and would take a lot of time, so it's lower on the priority list, especially since the reset button does the job for much less effort(for me lol)

**Comment by markusmo3** [comment]
TIL! This is a huuuuge feature in my opinion.
Maybe think about activating it by default?
Or at least having some hint that the class name is clickable for further settings?
As soon as I saw that gear icon I never thought about it having other setting windows.

Im also thinking about what happens when I don't open the webpage and click reset for a day.
Theoretically the day after that it should get twice the amount of rest bonus when clicking the reset button, right? Or is that also already a feature here? 😅

Anyways, great work and thanks!

**Comment by datmeal** [comment]
Sadly you'll just have to click reset twice if you skipped a day.
I kept that part manual just to keep things more simple for both ends, especially since if something happens and rest bonuses get messed up you can always set them up again.

It's so hard keeping things clean while adding new features!

**Comment by markusmo3** [comment]
Ah okay, good to know, thanks :)
Yeah, I can sympathize. Maybe just a little icon, a text hinting at it, or something, dunno.
This issue can be closed, these are just some suggestions and are totally up to you as functionally the main feature I wanted already existed 😅
